const config = {
  "translations": {
    "sk": {
      "journeySub": "A journey of us",
      "explore": "Explore",
      "spinLine1": "Roztočte glóbus a objavte naše spoločné chvíle.",
      "spinLine2": "Vyberte mesto a začnite.",
      "adventureLine1": "And now,",
      "adventureLine2": "Our new adventure begins.",
      "navIntro": "INTRO",
      "navJourney": "JOURNEY",
      "navWedding": "WEDDING",
      "selectCity": "VYBERTE MESTO",
      "introLine1": "Dve cesty.",
      "introLine2": "Jeden spoločný príbeh."
    }
  },
  "locations": [
    {
      "type": "text",
      "key": "vienna",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MTI3MTk4ODI1ODc5MjIw?story_media_id=4000542899596017726&stkn=NGxqMnJsbGRqNWZ5",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_1009",
      "name": "Vienna",
      "names": {
        "sk": "Viedeň",
        "en": "Vienna"
      },
      "lat": 48.2082,
      "lon": 16.3738,
      "countryCode": "AUT",
      "subname": "Rakúsko",
      "countryEn": "Austria",
      "side": "left"
    },
    {
      "type": "text",
      "key": "seville",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTg1NTQ1MjQxMTExODc1?story_media_id=4000551949467946375&stkn=ZGlzeWNvMjkwa3Uz",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_3098",
      "name": "Seville",
      "subname": "Španielsko",
      "lat": 37.3891,
      "lon": -5.9845,
      "side": "right",
      "x": "6%",
      "top": "33%",
      "names": {
        "sk": "Sevilla",
        "en": "Seville"
      },
      "countryCode": "ESP",
      "countryEn": "Spain"
    },
    {
      "type": "text",
      "key": "caminito-del-rey",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTA5NjE3MzUzMzEwMTE5?story_media_id=4000570806622536525&stkn=ODNwY3U3Y3RyeXpr",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_3217",
      "name": "Caminito del Rey",
      "names": {
        "sk": "Caminito del Rey",
        "en": "Caminito del Rey"
      },
      "lat": 36.91835,
      "lon": -4.77719,
      "countryCode": "ESP",
      "subname": "Španielsko",
      "countryEn": "Spain",
      "side": "left"
    },
    {
      "type": "text",
      "key": "marbella",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTk3MDY2NDUzMDQzMjU0?stkn=amhzcjk5YTR5OGpk",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_3290",
      "name": "Marbella",
      "names": {
        "sk": "Marbella",
        "en": "Marbella"
      },
      "lat": 36.5101,
      "lon": -4.8824,
      "countryCode": "ESP",
      "subname": "Španielsko",
      "countryEn": "Spain",
      "side": "right"
    },
    {
      "type": "image",
      "key": "granada",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MzUzODMzNDY4MTY5ODk0?story_media_id=4000580815876017575&stkn=dDU1a20wMXU5eHY1",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_3390",
      "name": "Granada",
      "subname": "Španielsko",
      "lat": 37.1773,
      "lon": -3.5986,
      "side": "left",
      "x": "6%",
      "top": "15%",
      "media": "photos/01-historic-selfie.jpeg",
      "names": {
        "sk": "Granada",
        "en": "Granada"
      },
      "countryCode": "ESP",
      "countryEn": "Spain"
    },
    {
      "type": "text",
      "key": "malaga",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTUwODI0MDA2MDQ4OTgy?story_media_id=4000729303173271228&stkn=MXd6aHlvanExandmbQ==",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_3504",
      "name": "Málaga",
      "subname": "Španielsko",
      "lat": 36.7213,
      "lon": -4.4214,
      "side": "right",
      "x": "6%",
      "top": "24%",
      "names": {
        "sk": "Malaga",
        "en": "Málaga"
      },
      "countryCode": "ESP",
      "countryEn": "Spain"
    },
    {
      "type": "image",
      "key": "london",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MTI0ODE2ODk4NDg0NjI2?story_media_id=4000739522819714123&stkn=MTE5cmhrM2Q2bnFkYg==",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_4209",
      "name": "London",
      "subname": "Spojené kráľovstvo",
      "lat": 51.5074,
      "lon": -0.1278,
      "side": "left",
      "x": "6%",
      "top": "33%",
      "media": "photos/02-west-ham.jpeg",
      "names": {
        "sk": "Londýn",
        "en": "London"
      },
      "countryCode": "GBR",
      "countryEn": "United Kingdom"
    },
    {
      "type": "image",
      "key": "madeira",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTAwMzM0MDQ4NjU2NjMy?stkn=MTRnYWQ3a2ZkMXR1MQ==",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_6011",
      "name": "Madeira",
      "subname": "Portugalsko",
      "lat": 32.7607,
      "lon": -16.9595,
      "side": "right",
      "x": "6%",
      "top": "42%",
      "media": "photos/03-madeira-waterfall.jpeg",
      "names": {
        "sk": "Madeira",
        "en": "Madeira"
      },
      "countryCode": "PRT",
      "countryEn": "Portugal"
    },
    {
      "type": "instagram",
      "key": "tokyo",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDYzMzQwNDUxMzQ3Mzk2?story_media_id=3706108608066373681&stkn=aWN5Y2YzeHF2eTB3",
      "instagramLabel": {
        "sk": "Viac z našej cesty v Tokiu",
        "en": "More from our journey in Tokyo"
      },
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_7011",
      "name": "Tokyo",
      "subname": "Japonsko",
      "lat": 35.6762,
      "lon": 139.6503,
      "side": "left",
      "x": "6%",
      "top": "60%",
      "media": "https://www.instagram.com/reel/DN_BgiWktOJ/embed/",
      "external": "https://www.instagram.com/reel/DN_BgiWktOJ/",
      "names": {
        "sk": "Tokio",
        "en": "Tokyo"
      },
      "countryCode": "JPN",
      "countryEn": "Japan"
    },
    {
      "type": "text",
      "key": "kyoto",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDYzMzQwNDUxMzQ3Mzk2?story_media_id=3707556566885742338&stkn=aWN5Y2YzeHF2eTB3",
      "name": "Kyoto",
      "names": {
        "sk": "Kjóto",
        "en": "Kyoto"
      },
      "lat": 35.0116,
      "lon": 135.7681,
      "countryCode": "JPN",
      "subname": "Japonsko",
      "countryEn": "Japan",
      "side": "right",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_7071"
    },
    {
      "type": "text",
      "key": "seoul",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MTAyMjQ0Mzg3NTkzNzM3?story_media_id=3709532771460474919&stkn=emJqOTBidnRnZDNk",
      "name": "Seoul",
      "subname": "Južná Kórea",
      "lat": 37.5665,
      "lon": 126.978,
      "side": "right",
      "x": "6%",
      "top": "42%",
      "names": {
        "sk": "Soul",
        "en": "Seoul"
      },
      "countryCode": "KOR",
      "countryEn": "South Korea",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_7371"
    },
    {
      "type": "text",
      "key": "beijing",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MTM4NzgzMDAxNDQxOTQ5?story_media_id=3711861645385043986&stkn=azhmaWVydWx6cXkx",
      "name": "Beijing",
      "subname": "Čína",
      "lat": 39.9042,
      "lon": 116.4074,
      "side": "left",
      "x": "6%",
      "top": "51%",
      "names": {
        "sk": "Peking",
        "en": "Beijing"
      },
      "countryCode": "CHN",
      "countryEn": "China",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_7616"
    },
    {
      "type": "text",
      "key": "manchester",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MzE3MjYyNjE5MjE2NDE3?story_media_id=3771360984317855128&stkn=aGtuaHR4bjF4cW1x",
      "name": "Manchester",
      "names": {
        "sk": "Manchester",
        "en": "Manchester"
      },
      "lat": 53.4808,
      "lon": -2.2426,
      "countryCode": "GBR",
      "subname": "Spojené kráľovstvo",
      "countryEn": "United Kingdom",
      "side": "right",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_8846"
    },
    {
      "type": "image",
      "key": "liverpool",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDk5OTAyMjk2ODE0Mjgw?story_media_id=3772172836350234131&stkn=MXYyMnkzcm82NnM4dA==",
      "name": "Liverpool",
      "subname": "Spojené kráľovstvo",
      "lat": 53.4084,
      "lon": -2.9916,
      "side": "left",
      "x": "6%",
      "top": "51%",
      "media": "photos/06-liverpool-waterfront.jpeg",
      "names": {
        "sk": "Liverpool",
        "en": "Liverpool"
      },
      "countryCode": "GBR",
      "countryEn": "United Kingdom",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_2853"
    },
    {
      "type": "text",
      "key": "carezza-dolomites",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDgzMzE2OTUyOTE3NDQx?story_media_id=3807811606843800394&stkn=dXRwb3JycnMycHcw",
      "name": "Carezza Dolomites",
      "names": {
        "sk": "Carezza Dolomites",
        "en": "Carezza Dolomites"
      },
      "lat": 46.4094,
      "lon": 11.57513,
      "countryCode": "ITA",
      "subname": "Taliansko",
      "countryEn": "Italy",
      "side": "right",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_9612"
    },
    {
      "type": "text",
      "key": "bologna",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDk5MTMyODA4OTkyOTM0?story_media_id=3867336931839375028&stkn=MTJodHA5bHQwMThrcA==",
      "name": "Bologna",
      "names": {
        "sk": "Bologna",
        "en": "Bologna"
      },
      "lat": 44.4949,
      "lon": 11.3426,
      "countryCode": "ITA",
      "subname": "Taliansko",
      "countryEn": "Italy",
      "side": "left",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_0331"
    },
    {
      "type": "image",
      "key": "florence",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE3ODU2OTYyNzQ4NjMxNTA2?story_media_id=3867746740908624398&stkn=eWY0NXozeDBmdnV1",
      "name": "Florence",
      "subname": "01 · 04 · 2026",
      "lat": 43.7696,
      "lon": 11.2558,
      "side": "right",
      "x": "6%",
      "top": "15%",
      "media": "photos/07-florence-engagement.jpeg",
      "special": "engagement",
      "names": {
        "sk": "Florencia",
        "en": "Florence"
      },
      "countryCode": "ITA",
      "countryEn": "Italy",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_0628"
    },
    {
      "type": "text",
      "key": "pisa",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDg2ODAxMjc5NTkzMzcz?story_media_id=3868560024591193463&stkn=MWJ4OWN2ODY4Y3l2NQ==",
      "name": "Pisa",
      "names": {
        "sk": "Pisa",
        "en": "Pisa"
      },
      "lat": 43.7228,
      "lon": 10.4017,
      "countryCode": "ITA",
      "subname": "Taliansko",
      "countryEn": "Italy",
      "side": "left",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_0723"
    },
    {
      "type": "text",
      "key": "prague",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE3ODgxNzMyODU0NTY2ODc3?story_media_id=3892481681969963795&stkn=dDJ2cGl4OG1ocmJk",
      "name": "Prague",
      "names": {
        "sk": "Praha",
        "en": "Prague"
      },
      "lat": 50.0755,
      "lon": 14.4378,
      "countryCode": "CZE",
      "subname": "Česko",
      "countryEn": "Czechia",
      "side": "right",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_1243"
    },
    {
      "type": "text",
      "key": "sardinia",
      "instagramHighlight": "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDU5MDYxMTY3NTQ2NzM1?story_media_id=4000762126645334557&stkn=MWFqZ215ZG1sMXJxeQ==",
      "name": "Sardinia",
      "subname": "Taliansko",
      "lat": 40.12,
      "lon": 9.01,
      "side": "left",
      "x": "6%",
      "top": "60%",
      "names": {
        "sk": "Sardínia",
        "en": "Sardinia"
      },
      "countryCode": "ITA",
      "countryEn": "Italy",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_2437"
    },
    {
      "type": "image",
      "key": "trnava",
      "name": "Trnava",
      "subname": "Slovensko",
      "lat": 48.3774,
      "lon": 17.5883,
      "side": "right",
      "x": "6%",
      "top": "24%",
      "media": "photos/08-formal-outdoor.jpeg",
      "description": "Miesto, kde sme sa rozhodli žiť.",
      "descriptionEn": "The place we chose to call home.",
      "names": {
        "sk": "Trnava",
        "en": "Trnava"
      },
      "countryCode": "SVK",
      "countryEn": "Slovakia",
      "fullscreenVideo": "https://res.cloudinary.com/kxksv8hk/video/upload/w_1080,q_auto,f_auto/IMG_0800"
    }
  ],
  "GLOBE_RADIUS": 12,
  "intro": {
    "poster": null,
    "video": "https://res.cloudinary.com/kxksv8hk/video/upload/eo_6.57,w_1080,q_auto,f_auto/IMG_5897"
  },
  "wedding": {
    "couple": {
      "first": "Simona",
      "second": "Martin",
      "full": "Simona & Martin"
    },
    "dateLabel": "30 · 04 · 2027",
    "date": "2027-04-30T00:00:00+02:00",
    "ceremony": {
      "name": "Kostol sv. Jakuba",
      "address": "Františkánska 1, 917 01 Trnava",
      "time": "15:00",
      "maps": "https://maps.google.com/?q=Kostol+sv.+Jakuba,+Franti%C5%A1k%C3%A1nska+1,+Trnava",
      "website": "https://frantiskani.sk/trnava/"
    },
    "reception": {
      "name": "Penzión Zemiansky dvor",
      "address": "Krakovská 67, 919 25 Šúrovce",
      "time": "Po obrade",
      "maps": "https://maps.google.com/?q=Penzion+Zemiansky+dvor,+Krakovska+67,+Surovce",
      "website": "https://lareunion.sk/penzion-zemiansky-dvor-surovce/"
    },
    "rsvpEndpoint": "https://script.google.com/macros/s/AKfycbw1rK7Ihb3XUxz0ab5tx9l3Le5j0V8xbl72BRsg_dRdHGy6Z0PCzWhZzRyagxTa3KGrlg/exec",
    "menuCourses": [],
    "timeline": [
      {
        "time": "14:00",
        "titleKey": "wGatheringTitle",
        "detailKey": "wGatheringDetail",
        "icon": "gathering"
      },
      {
        "time": "14:15",
        "titleKey": "wBusTitle",
        "detailKey": "wBusDetail",
        "icon": "bus"
      },
      {
        "time": "15:00",
        "titleKey": "wCeremonyTitle",
        "detailKey": "wCeremonyDetail",
        "icon": "church"
      },
      {
        "timeKey": "wAfterCeremony",
        "titleKey": "wReceptionTitle",
        "detailKey": "wReceptionDetail",
        "icon": "rings"
      }
    ],
    "faq": [
      {
        "questionKey": "wFaqCeremonyQ",
        "answerKey": "wFaqCeremonyA",
        "links": [
          {
            "url": "https://maps.google.com/?q=Kostol+sv.+Jakuba,+Franti%C5%A1k%C3%A1nska+1,+Trnava",
            "labelKey": "wMap"
          },
          {
            "url": "https://frantiskani.sk/trnava/",
            "labelKey": "wChurch"
          }
        ]
      },
      {
        "questionKey": "wFaqReceptionQ",
        "answerKey": "wFaqReceptionA",
        "links": [
          {
            "url": "https://maps.google.com/?q=Penzion+Zemiansky+dvor,+Krakovska+67,+Surovce",
            "labelKey": "wMap"
          },
          {
            "url": "https://lareunion.sk/penzion-zemiansky-dvor-surovce/",
            "labelKey": "wVenue"
          },
          {
            "url": "https://my.vpromo.sk/sk/tour/zemiansky-dvor",
            "labelKey": "wTour"
          }
        ]
      },
      {
        "questionKey": "wFaqTransportQ",
        "answerKey": "wFaqTransportA"
      },
      {
        "questionKey": "wFaqParkingQ",
        "answerKey": "wFaqParkingA",
        "links": [
          {
            "url": "https://maps.app.goo.gl/ciaJPLoRWqoJTocd8",
            "labelKey": "wParking"
          }
        ]
      },
      {
        "questionKey": "wFaqLodgingQ",
        "answerKey": "wFaqLodgingA",
        "links": [
          {
            "url": "https://www.penzionzemianskydvor.sk/ubytovanie/",
            "labelKey": "wBooking"
          }
        ]
      },
      {
        "questionKey": "wFaqDressQ",
        "answerKey": "wFaqDressA"
      },
      {
        "questionKey": "wFaqGiftsQ",
        "answerKey": "wFaqGiftsA"
      },
      {
        "questionKey": "wFaqDietQ",
        "answerKey": "wFaqDietA",
        "tab": "rsvp"
      },
      {
        "questionKey": "wFaqRsvpQ",
        "answerKey": "wFaqRsvpA",
        "tab": "rsvp"
      },
      {
        "questionKey": "wFaqContactQ",
        "answerKey": "wFaqContactA"
      }
    ]
  },
  "audio": {
    "backgroundMusic": null
  },
  "gallery": {
    "url": null
  },
  "ui": {
    "sk": {
      "wInvitation": "Svadobná pozvánka",
      "wAnd": "a",
      "wAnnounce": "S radosťou vám oznamujeme,",
      "wSacrament": "že uzatvárame sviatosť manželstva",
      "wInvitationDate": "30. apríla 2027",
      "wInvitationPlace": "v Kostole sv. Jakuba v Trnave",
      "wInvitationMeeting": "14:00 · stretnutie v Šúrovciach",
      "wInformation": "Svadobné informácie",
      "story": "NÁŠ SPOLOČNÝ PRÍBEH",
      "navIntro": "ÚVOD",
      "navJourney": "CESTA",
      "navWedding": "SVADBA",
      "introStatus": "Simona a Martin. Náš spoločný príbeh.",
      "skip": "Preskočiť",
      "loading": "Načítavanie",
      "explore": "OBJAVIŤ",
      "intro1": "Dve cesty.",
      "intro2": "Jeden spoločný príbeh.",
      "journey1": "Roztočte glóbus a objavte naše spoločné chvíle.",
      "journey2": "Vyberte mesto a začnite.",
      "prepare": "Pripravujeme glóbus našich ciest.",
      "select": "Vyberte mesto alebo otočte glóbus.",
      "canvas": "Glóbus: potiahnutím otáčajte, dvoma prstami približujte; mesto vyberiete aj tlačidlom.",
      "fallback": "Glóbus sa nepodarilo zobraziť. Spomienky otvoríte výberom mesta.",
      "videoLoading": "Načítavam spomienku…",
      "videoTap": "Ťuknutím spustíte video.",
      "videoError": "Video sa nepodarilo načítať.",
      "play": "Prehrať video",
      "back": "Späť na cestu",
      "close": "Zatvoriť spomienku",
      "imageError": "Fotografiu sa nepodarilo načítať.",
      "instagram": "POZRIEŤ NA INSTAGRAME ↗",
      "more": "Viac z našej cesty",
      "gallery": "Fotografie zo svadby už čoskoro.",
      "photos": "Svadobné fotografie",
      "soundOn": "Vypnúť hudbu",
      "soundOff": "Zapnúť hudbu",
      "noMusic": "Hudbu doplníme čoskoro.",
      "dark": "Prepnúť na tmavú náladu",
      "light": "Prepnúť na svetlú náladu",
      "language": "Prepnúť do angličtiny",
      "controls": "Globálne ovládanie",
      "next": "Ďalšia",
      "wedding": "Naša svadba",
      "engagement": "Zásnuby",
      "memory": "Spomienka",
      "of": "zo",
      "videoMemory": "Video spomienka.",
      "final1": "A teraz,",
      "final2": "Začína sa naše nové dobrodružstvo.",
      "home": "Simona a Martin — späť na intro",
      "navigation": "Navigácia príbehu",
      "cities": "Mestá",
      "moreFromTrip": "Pozrieť viac z tejto cesty",
      "nextJourney": "ĎALŠIA CESTA",
      "previousJourney": "PREDCHÁDZAJÚCA CESTA",
      "comingSoon": "Spomienky doplníme čoskoro.",
      "storyPlay": "Prehrať náš príbeh",
      "storyContinue": "Pokračovať v príbehu",
      "storyExplore": "OBJAVOVAŤ GLÓBUS",
      "storyPause": "Pozastaviť príbeh",
      "storyHint": "Príbeh sa spustí automaticky. Ťuknutím prejdete na objavovanie.",
      "journeyEntry": "Naše spoločné cesty.",
      "wTabs": "Svadobné informácie",
      "wDetail": "DETAIL",
      "wProgram": "PROGRAM",
      "wMenu": "MENU",
      "wRsvp": "RSVP",
      "wFaq": "FAQ",
      "wChapter": "NAŠA SVADBA",
      "wDate": "30. apríla 2027",
      "wWelcome": "Tešíme sa, že tento deň budete prežívať spolu s nami.",
      "wCountdown": "Do nášho dňa zostáva",
      "wDays": "DNÍ",
      "wHours": "HODÍN",
      "wMinutes": "MINÚT",
      "wSeconds": "SEKÚND",
      "wDayArrived": "Náš spoločný deň.",
      "wCeremony": "OBRAD",
      "wReception": "OSLAVA",
      "wAfterCeremony": "Po obrade",
      "wMap": "Zobraziť na mape",
      "wChurch": "O kostole",
      "wVenue": "O mieste oslavy",
      "wTour": "Prehliadka Zemianskeho dvora",
      "wTransport": "DOPRAVA",
      "wTransportShort": "Zo Šúroviec spolu autobusom o 14:15 alebo priamo ku kostolu v Trnave.",
      "wLodging": "UBYTOVANIE",
      "wLodgingShort": "Z 30. apríla na 1. mája priamo v Zemianskom dvore. Dostupnosť a rezerváciu si overte v penzióne.",
      "wPractical": "Praktické informácie",
      "wConfirm": "Potvrdiť účasť",
      "wProgramTitle": "Náš svadobný deň",
      "wProgramIntro": "Tešíme sa na každý spoločný okamih.",
      "wGatheringTitle": "Stretnutie v Šúrovciach",
      "wGatheringDetail": "Miesto nástupu na autobus doplníme.",
      "wBusTitle": "Odchod autobusu",
      "wBusDetail": "Zo Šúroviec do Trnavy.",
      "wCeremonyTitle": "Svadobný obrad",
      "wCeremonyDetail": "Kostol sv. Jakuba · Trnava",
      "wReceptionTitle": "Svadobná oslava",
      "wReceptionDetail": "Penzión Zemiansky dvor · Šúrovce",
      "wMenuTitle": "Pri jednom stole",
      "wMenuPendingTitle": "Na dobré veci sa oplatí počkať.",
      "wMenuPending": "Na detailoch nášho svadobného menu ešte pracujeme. Kompletné menu zverejníme čoskoro.",
      "wDietTitle": "S ohľadom na každého",
      "wDiet": "Vegetariánske, bezlepkové a iné diétne požiadavky nám, prosím, uveďte pri potvrdení účasti.",
      "wRsvpTitle": "Budete pri tom?",
      "wRsvpIntro": "Vaša odpoveď nám pomôže pripraviť náš spoločný deň.",
      "wFaqTitle": "Dobré vedieť",
      "wFaqIntro": "Malé odpovede na veľký deň.",
      "wFaqCeremonyQ": "Kde a kedy sa koná obrad?",
      "wFaqCeremonyA": "Svadobný obrad sa uskutoční 30. apríla 2027 o 15:00 v Kostole sv. Jakuba, Františkánska 1, 917 01 Trnava.",
      "wFaqReceptionQ": "Kde budeme oslavovať?",
      "wFaqReceptionA": "Po obrade sa stretneme na svadobnej oslave v Penzióne Zemiansky dvor, Krakovská 67, 919 25 Šúrovce.",
      "wFaqTransportQ": "Ako sa dostaneme na svadbu?",
      "wFaqTransportA": "O 14:00 sa stretneme v Šúrovciach. Autobus odchádza o 14:15 do Trnavy; presné miesto nástupu doplníme. Môžete prísť aj priamo pred Kostol sv. Jakuba. V RSVP nám, prosím, dajte vedieť, ktorú možnosť využijete. Po oslave autobus odvezie hostí späť do Šúroviec.",
      "wFaqParkingQ": "Kde môžeme zaparkovať?",
      "wFaqParkingA": "Parkovanie pri kostole nájdete na priloženej mape.",
      "wParking": "Parkovanie pri kostole",
      "wFaqLodgingQ": "Je možné zostať na noc?",
      "wFaqLodgingA": "Penzión Zemiansky dvor ponúka 9 izieb priamo v areáli. Ak máte záujem o noc z 30. apríla na 1. mája 2027, dostupnosť a rezerváciu si overte priamo v penzióne. V RSVP uveďte počet osôb, ktoré majú o ubytovanie záujem; odpoveď v RSVP nenahrádza rezerváciu.",
      "wBooking": "Informácie a rezervácia",
      "wFaqDressQ": "Čo si máme obliecť?",
      "wFaqDressA": "Zvoľte si oblečenie, v ktorom sa budete cítiť slávnostne a pohodlne. Ďalšie odporúčania doplníme.",
      "wFaqGiftsQ": "Čo svadobné dary?",
      "wFaqGiftsA": "Najväčším darom pre nás bude, že tento deň oslávite spolu s nami. Ak by ste nás chceli obdarovať aj niečím navyše, veľmi nás poteší finančný príspevok do nášho spoločného začiatku.",
      "wFaqDietQ": "Čo ak mám alergiu alebo špeciálne stravovanie?",
      "wFaqDietA": "Vegetariánske, bezlepkové a ďalšie diétne požiadavky nám napíšte do RSVP. Kompletné svadobné menu ešte pripravujeme.",
      "wFaqRsvpQ": "Ako a dokedy potvrdiť účasť?",
      "wFaqRsvpA": "Vyplňte RSVP priamo tu na stránke. Uveďte mená hostí, účasť a prípadné požiadavky na dopravu, ubytovanie či stravu. Termín potvrdenia ešte doplníme.",
      "wFaqContactQ": "Na koho sa obrátiť s ďalšími otázkami?",
      "wFaqContactA": "Budeme radi, keď sa ozvete. Kontaktné údaje a e-mail doplníme. Odkaz nám zatiaľ môžete nechať pri potvrdení účasti.",
      "wThanks": "Tešíme sa na vás.",
      "rsvpParticipation": "Účasť",
      "rsvpGuests": "Hostia",
      "rsvpTransport": "Doprava",
      "rsvpAccommodation": "Ubytovanie",
      "rsvpDetails": "Detaily",
      "rsvpChooseOne": "Vyberte jednu možnosť",
      "rsvpAttendanceQuestion": "Prídete na našu svadbu?",
      "rsvpYes": "Áno, prídeme",
      "rsvpNo": "Nie, neprídeme",
      "rsvpNamesAttending": "Koľko vás príde?",
      "rsvpNamesDeclining": "Za koho posielate odpoveď?",
      "rsvpNamesNote": "Uveďte všetkých hostí a meno každej osoby samostatne.",
      "rsvpNamesDecliningNote": "Uveďte mená osôb, za ktoré potvrdzujete neúčasť.",
      "rsvpGuestCount": "Počet osôb",
      "rsvpGuestName": "Meno osoby",
      "rsvpDecrease": "Znížiť počet osôb",
      "rsvpIncrease": "Zvýšiť počet osôb",
      "rsvpTransportQuestion": "Ako sa k nám dostanete?",
      "rsvpTransportNote": "Vyberte dopravu pre vašu skupinu. Autobus vás po oslave odvezie späť do Šúroviec.",
      "rsvpBus": "Autobus zo Šúroviec · odchod 14:15",
      "rsvpDirect": "Prídeme priamo ku kostolu",
      "rsvpLodgingQuestion": "Máte záujem o ubytovanie?",
      "rsvpLodgingNote": "Penzión Zemiansky dvor ponúka ubytovanie priamo v Šúrovciach. Dostupnosť a rezerváciu si overte priamo v penzióne. Táto odpoveď vyjadruje záujem, nie rezerváciu.",
      "rsvpLodgingYes": "Áno, máme záujem",
      "rsvpLodgingNo": "Nie, nebudeme potrebovať",
      "rsvpLodgingCount": "Počet osôb so záujmom o ubytovanie",
      "rsvpLodgingDates": "Z 30. apríla na 1. mája 2027.",
      "rsvpDetailsQuestion": "Ešte pár maličkostí",
      "rsvpOptional": "Nasledujúce odpovede sú dobrovoľné.",
      "rsvpDietary": "Alergie alebo špeciálne stravovanie",
      "rsvpMusic": "Pesnička, na ktorú si chcete zatancovať",
      "rsvpMessage": "Odkaz pre nás",
      "rsvpReviewTitle": "Je všetko správne?",
      "rsvpPrivacy": "Odpoveď uložíme do našej súkromnej svadobnej tabuľky a použijeme ju na prípravu svadby.",
      "rsvpBack": "Späť",
      "rsvpEdit": "Upraviť odpoveď",
      "rsvpNext": "Pokračovať",
      "rsvpReview": "Skontrolovať odpoveď",
      "rsvpSend": "Odoslať odpoveď",
      "rsvpSending": "Odosielame…",
      "rsvpSendingNote": "Prosíme, chvíľu počkajte na potvrdenie.",
      "rsvpReceived": "Odpoveď bola uložená",
      "rsvpThanks": "Ďakujeme!",
      "rsvpThanksYes": "Vašu odpoveď sme uložili. Tešíme sa, že náš deň oslávime spolu.",
      "rsvpThanksNo": "Vašu odpoveď sme uložili. Ďakujeme, že ste nám dali vedieť.",
      "rsvpAttendanceError": "Vyberte, prosím, či sa svadby zúčastníte.",
      "rsvpNamesError": "Doplňte, prosím, meno každej osoby.",
      "rsvpTransportError": "Vyberte, prosím, spôsob dopravy.",
      "rsvpLodgingError": "Vyberte, prosím, odpoveď k ubytovaniu.",
      "rsvpUnavailable": "Formulár sa ešte pripravuje. Skúste to, prosíme, neskôr.",
      "rsvpSendError": "Odpoveď sa nepodarilo uložiť. Skontrolujte pripojenie a skúste to znova.",
      "rsvpUnconfirmed": "Potvrdenie uloženia zatiaľ neprišlo. Odpoveď mohla byť doručená; vaše údaje tu zostali. Pred opakovaným odoslaním si doručenie overte s nami, aby nevznikla duplicita.",
      "rsvpRetry": "Odoslať znovu",
      "rsvpSubmissionFrame": "Odoslanie svadobnej odpovede"
    },
    "en": {
      "wInvitation": "Wedding invitation",
      "wAnd": "and",
      "wAnnounce": "With joy, we announce",
      "wSacrament": "that we will be united in the sacrament of marriage",
      "wInvitationDate": "30 April 2027",
      "wInvitationPlace": "at the Church of St. James in Trnava",
      "wInvitationMeeting": "14:00 · gathering in Šúrovce",
      "wInformation": "Wedding details",
      "story": "A JOURNEY OF US",
      "navIntro": "INTRO",
      "navJourney": "JOURNEY",
      "navWedding": "WEDDING",
      "introStatus": "Simona and Martin. A journey of us.",
      "skip": "Skip",
      "loading": "Loading",
      "explore": "EXPLORE",
      "intro1": "Two paths.",
      "intro2": "One shared story.",
      "journey1": "Spin the globe and discover our moments together.",
      "journey2": "Choose a city to begin.",
      "prepare": "Preparing the globe of our travels.",
      "select": "Choose a city or rotate the globe.",
      "canvas": "Globe: drag to rotate, pinch to zoom; you can also select a city using its button.",
      "fallback": "The globe could not load. Select a city to open a memory.",
      "videoLoading": "Loading our memory…",
      "videoTap": "Tap to play the video.",
      "videoError": "The video could not load.",
      "play": "Play video",
      "back": "Back to Journey",
      "close": "Close memory",
      "imageError": "The photo could not load.",
      "instagram": "VIEW ON INSTAGRAM ↗",
      "more": "More from our journey",
      "gallery": "Wedding photos coming soon.",
      "photos": "Wedding photos",
      "soundOn": "Turn music off",
      "soundOff": "Turn music on",
      "noMusic": "Music is coming soon.",
      "dark": "Switch to dark mood",
      "light": "Switch to light mood",
      "language": "Switch to Slovak",
      "controls": "Global controls",
      "next": "Next",
      "wedding": "Our wedding",
      "engagement": "Engagement",
      "memory": "Memory",
      "of": "of",
      "videoMemory": "Video memory.",
      "final1": "And now,",
      "final2": "Our new adventure begins.",
      "home": "Simona and Martin — back to intro",
      "navigation": "Story navigation",
      "cities": "Cities",
      "moreFromTrip": "See more from this trip",
      "nextJourney": "NEXT JOURNEY",
      "previousJourney": "PREVIOUS JOURNEY",
      "comingSoon": "Memories coming soon.",
      "storyPlay": "Play our story",
      "storyContinue": "Continue our story",
      "storyExplore": "EXPLORE THE GLOBE",
      "storyPause": "Pause our story",
      "storyHint": "Our story starts automatically. Tap to explore on your own.",
      "journeyEntry": "Our journeys together.",
      "wTabs": "Wedding information",
      "wDetail": "DETAIL",
      "wProgram": "TIMELINE",
      "wMenu": "MENU",
      "wRsvp": "RSVP",
      "wFaq": "FAQ",
      "wChapter": "OUR WEDDING",
      "wDate": "April 30, 2027",
      "wWelcome": "We are so happy to share this day with you.",
      "wCountdown": "Until our day",
      "wDays": "DAYS",
      "wHours": "HOURS",
      "wMinutes": "MINS",
      "wSeconds": "SECS",
      "wDayArrived": "Our day together.",
      "wCeremony": "CEREMONY",
      "wReception": "CELEBRATION",
      "wAfterCeremony": "After the ceremony",
      "wMap": "View on map",
      "wChurch": "About the church",
      "wVenue": "About the venue",
      "wTour": "Explore Zemiansky dvor",
      "wTransport": "GETTING THERE",
      "wTransportShort": "Join the bus from Šúrovce at 14:15, or meet us directly at the church in Trnava.",
      "wLodging": "STAYING THE NIGHT",
      "wLodgingShort": "April 30 to May 1 at Zemiansky dvor. Please check availability and book directly with the guesthouse.",
      "wPractical": "Practical information",
      "wConfirm": "Confirm attendance",
      "wProgramTitle": "Our wedding day",
      "wProgramIntro": "Looking forward to every moment together.",
      "wGatheringTitle": "Gathering in Šúrovce",
      "wGatheringDetail": "The exact bus boarding point will be announced.",
      "wBusTitle": "Bus departure",
      "wBusDetail": "From Šúrovce to Trnava.",
      "wCeremonyTitle": "Wedding ceremony",
      "wCeremonyDetail": "Kostol sv. Jakuba · Trnava",
      "wReceptionTitle": "Wedding celebration",
      "wReceptionDetail": "Penzión Zemiansky dvor · Šúrovce",
      "wMenuTitle": "At the same table",
      "wMenuPendingTitle": "Good things are worth the wait.",
      "wMenuPending": "We are still putting the finishing touches on our wedding menu. The full menu is coming soon.",
      "wDietTitle": "A place for everyone",
      "wDiet": "Please let us know about vegetarian, gluten-free or other dietary requirements in your RSVP.",
      "wRsvpTitle": "Will you join us?",
      "wRsvpIntro": "Your reply will help us prepare our day together.",
      "wFaqTitle": "Good to know",
      "wFaqIntro": "Small answers for the big day.",
      "wFaqCeremonyQ": "Where and when is the ceremony?",
      "wFaqCeremonyA": "Our wedding ceremony takes place on April 30, 2027 at 15:00 at Kostol sv. Jakuba, Františkánska 1, 917 01 Trnava.",
      "wFaqReceptionQ": "Where will we celebrate?",
      "wFaqReceptionA": "After the ceremony, join us for the celebration at Penzión Zemiansky dvor, Krakovská 67, 919 25 Šúrovce.",
      "wFaqTransportQ": "How do we get to the wedding?",
      "wFaqTransportA": "We will meet in Šúrovce at 14:00. The bus leaves for Trnava at 14:15; we will announce the exact boarding point. You can also come directly to Kostol sv. Jakuba. Please select your preference in the RSVP. After the celebration, the bus will take guests back to Šúrovce.",
      "wFaqParkingQ": "Where can we park?",
      "wFaqParkingA": "Please see the linked map for parking near the church.",
      "wParking": "Parking near the church",
      "wFaqLodgingQ": "Can we stay overnight?",
      "wFaqLodgingA": "Penzión Zemiansky dvor has 9 rooms on site. For the night of April 30 to May 1, 2027, please check availability and book directly with the guesthouse. Include the number of people interested in accommodation in your RSVP; an RSVP does not make a room reservation.",
      "wBooking": "Information and booking",
      "wFaqDressQ": "What should we wear?",
      "wFaqDressA": "Choose something festive that you feel comfortable in. We will add further recommendations.",
      "wFaqGiftsQ": "What about wedding gifts?",
      "wFaqGiftsA": "Celebrating this day with you is the greatest gift. If you would like to give us something more, a contribution towards the beginning of our life together would mean a lot to us.",
      "wFaqDietQ": "What if I have allergies or dietary requirements?",
      "wFaqDietA": "Please tell us about vegetarian, gluten-free or other dietary requirements in your RSVP. We are still preparing the full wedding menu.",
      "wFaqRsvpQ": "How and when should we RSVP?",
      "wFaqRsvpA": "Use the RSVP here on this page. Include guest names, attendance and any transport, accommodation or dietary requirements. The reply deadline will be announced.",
      "wFaqContactQ": "Who can I contact with other questions?",
      "wFaqContactA": "We would love to hear from you. Contact details and an email address will be added. For now, you can leave us a message in your RSVP.",
      "wThanks": "We cannot wait to see you.",
      "rsvpParticipation": "Attendance",
      "rsvpGuests": "Guests",
      "rsvpTransport": "Transport",
      "rsvpAccommodation": "Accommodation",
      "rsvpDetails": "Details",
      "rsvpChooseOne": "Choose one option",
      "rsvpAttendanceQuestion": "Will you join us?",
      "rsvpYes": "Yes, we will be there",
      "rsvpNo": "Sorry, we cannot attend",
      "rsvpNamesAttending": "How many of you will join us?",
      "rsvpNamesDeclining": "Who are you replying for?",
      "rsvpNamesNote": "Include everyone in your group and enter each person's name separately.",
      "rsvpNamesDecliningNote": "Enter the names of everyone whose absence you are confirming.",
      "rsvpGuestCount": "Number of people",
      "rsvpGuestName": "Guest name",
      "rsvpDecrease": "Decrease the number of people",
      "rsvpIncrease": "Increase the number of people",
      "rsvpTransportQuestion": "How will you get there?",
      "rsvpTransportNote": "Choose transport for your group. The bus will take guests back to Šúrovce after the celebration.",
      "rsvpBus": "Bus from Šúrovce · departs 14:15",
      "rsvpDirect": "We will go directly to the church",
      "rsvpLodgingQuestion": "Would you like accommodation?",
      "rsvpLodgingNote": "Penzión Zemiansky dvor offers rooms in Šúrovce. Please check availability and book directly with the guesthouse. This answer expresses interest and is not a reservation.",
      "rsvpLodgingYes": "Yes, we are interested",
      "rsvpLodgingNo": "No, we will not need it",
      "rsvpLodgingCount": "People interested in accommodation",
      "rsvpLodgingDates": "The night of 30 April–1 May 2027.",
      "rsvpDetailsQuestion": "A few little details",
      "rsvpOptional": "The following answers are optional.",
      "rsvpDietary": "Allergies or dietary requirements",
      "rsvpMusic": "A song you would love to dance to",
      "rsvpMessage": "A message for us",
      "rsvpReviewTitle": "Does everything look right?",
      "rsvpPrivacy": "We will save your reply in our private wedding spreadsheet and use it to prepare for the wedding.",
      "rsvpBack": "Back",
      "rsvpEdit": "Edit reply",
      "rsvpNext": "Continue",
      "rsvpReview": "Review reply",
      "rsvpSend": "Send reply",
      "rsvpSending": "Sending…",
      "rsvpSendingNote": "Please wait a moment for confirmation.",
      "rsvpReceived": "Your reply has been saved",
      "rsvpThanks": "Thank you!",
      "rsvpThanksYes": "Your reply has been saved. We are looking forward to celebrating with you.",
      "rsvpThanksNo": "Your reply has been saved. Thank you for letting us know.",
      "rsvpAttendanceError": "Please choose whether you will attend.",
      "rsvpNamesError": "Please enter every person's name.",
      "rsvpTransportError": "Please choose your transport.",
      "rsvpLodgingError": "Please answer the accommodation question.",
      "rsvpUnavailable": "The form is being prepared. Please try again later.",
      "rsvpSendError": "Your reply could not be saved. Please check your connection and try again.",
      "rsvpUnconfirmed": "We have not received a save confirmation yet. Your reply may have arrived; your details are still here. Please check with us before sending again to avoid a duplicate.",
      "rsvpRetry": "Send again",
      "rsvpSubmissionFrame": "Wedding reply submission"
    }
  },
  "countryEnglish": {
    "granada": "Spain",
    "trnava": "Our home",
    "malaga": "Spain",
    "sevilla": "Spain",
    "seoul": "South Korea",
    "beijing": "China",
    "sardinia": "Italy"
  }
};
export default config;
