export const galleryData = [
  { file: '01-historic-selfie.jpeg', place: 'Hlohovec · Cífer · a cesty medzi tým', title: 'Jeden<br><em>príbeh.</em>', text: 'Dva začiatky. Dve cesty. A potom sa stretli. Simona & Martin — odvtedy jedným smerom.', alt: 'Simona a Martin na spoločnej selfie pred historickými budovami', color: '#37342b', accent: '#b89a70' },
  { file: '02-west-ham.jpeg', place: 'Londýn · West Ham', title: 'Na jednej<br><em>strane.</em>', text: 'Veľké zážitky aj malé radosti. Najlepšie sú tie, ktoré môžeme prežívať spolu.', alt: 'Spoločná selfie Simony a Martina na West Hame', color: '#342c37', accent: '#b096ab' },
  { file: '03-madeira-waterfall.jpeg', place: 'Madeira · pri vodopáde', title: 'O kúsok<br><em>ďalej.</em>', text: 'Za novými výhľadmi. Za dobrodružstvom. Za spomienkami, ktoré si berieme domov.', alt: 'Simona a Martin pri vodopáde na Madeire', color: '#223a34', accent: '#92ac91' },
  { file: '04-madeira-swing.jpeg', place: 'Madeira · výhľad pre dvoch', title: 'Len tak<br><em>byť.</em>', text: 'Niektoré chvíle nepotrebujú veľa slov. Stačí výhľad, pokoj a ten druhý vedľa nás.', alt: 'Simona a Martin na hojdačkách s výhľadom na Madeire', color: '#2c3b39', accent: '#adc0b0' },
  { file: '05-madeira-hats.jpeg', place: 'Madeira · cestou necestou', title: 'Trochu<br><em>blázniví.</em>', text: 'Aj toto sme my. Smiech, spontánne nápady a obyčajné chvíle, na ktoré sa nezabúda.', alt: 'Simona a Martin s klobúkmi v aute na Madeire', color: '#3d372c', accent: '#c3ab82' },
  { file: '06-liverpool-waterfront.jpeg', place: 'Liverpool · pri vode', title: 'V každom<br><em>počasí.</em>', text: 'Nech nás cesta zavedie kamkoľvek, máme svoje miesto. Jeden pri druhom.', alt: 'Simona a Martin pri nábreží v Liverpoole', color: '#293740', accent: '#94aab6' },
  { file: '07-florence-engagement.jpeg', place: 'Florencia · naše áno', title: 'Jedno malé<br><em>áno.</em>', text: 'A celý život pred nami. Florencia sa stala miestom, kde sa náš príbeh otvoril novej kapitole.', alt: 'Zásnubná selfie Simony a Martina v nočnej Florencii s prsteňom', color: '#302c3b', accent: '#c2a48a' },
  { file: '08-formal-outdoor.jpeg', place: 'Simona & Martin', title: 'Stále<br><em>my dvaja.</em>', text: 'Na cestách aj doma. V slávnostných chvíľach aj v tých celkom obyčajných.', alt: 'Simona a Martin v spoločenskom oblečení vonku', color: '#343b2b', accent: '#b5b58c' },
  { file: '09-formal-mirror.jpeg', place: '30. apríla 2027 · naša ďalšia kapitola', title: 'A teraz<br><em>navždy.</em>', text: 'Náš príbeh pokračuje. Budeme radi, keď budete pri ďalšej kapitole s nami.', alt: 'Elegantná spoločná zrkadlová fotografia Simony a Martina', color: '#3c302c', accent: '#c8ab97' },
]
